AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1 # Assuming a reasonably modern Ruby version

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120
